In [1]:
import csv

In [5]:
with open("/home/AIML_Student/Documents/210962206/Week1/sheet1.csv",'rt') as f:
    data = csv.reader(f)
    for row in data:
        print(row)

['Programming Language', 'Designed by', 'Appeared', 'Extension']
['Python ', 'Guido Van Rossum', '1991', '.py']
['Java ', 'James Gosling', '1995', '.java']
['C++ ', 'Bjarne Strousstrup', '1983', '.cpp']


In [10]:
with open("/home/AIML_Student/Documents/210962206/Week1/sheet2.csv",mode = 'w') as file:
    writer = csv.writer(file,delimiter = ",",quotechar = '"',quoting = csv.QUOTE_MINIMAL)
    writer.writerow(['Programming Language', 'Designed by', 'Appeared', 'Extension'])
    writer.writerow(['Python ', 'Guido Van Rossum', '1991', '.py'])
    writer.writerow(['Java ', 'James Gosling', '1995', '.java'])
    writer.writerow(['C++ ', 'Bjarne Strousstrup', '1983', '.cpp'])
    writer.writerow(['C',"XYZ","1975",'.c'])

In [11]:
with open("/home/AIML_Student/Documents/210962206/Week1/sheet2.csv",'rt') as f:
    data = csv.reader(f)
    for row in data:
        print(row)

['Programming Language', 'Designed by', 'Appeared', 'Extension']
['Python ', 'Guido Van Rossum', '1991', '.py']
['Java ', 'James Gosling', '1995', '.java']
['C++ ', 'Bjarne Strousstrup', '1983', '.cpp']
['C', 'XYZ', '1975', '.c']


In [13]:
with open("/home/AIML_Student/Documents/210962206/Week1/sheet3.csv",'rt') as f:
    data = csv.reader(f)
    for row in data:
        print(row)

['Programming_Language', 'Designed by', 'Appeared', 'Extension']
['Python', 'Guido Van Rossum', '1991', '.py']
['Java', 'James Gosling', '1995', '.java']
['C++', 'Bjarne Stroustrup', '1983', '.cpp']
['JavaScript', 'ABCD', '1999', '.js']


In [12]:
import pandas as pd

In [13]:
import pandas as pd
d= {"Programming Langauge":["Python","Java","C++"],"Designed by":["Guido","James","Bjarne"],"Appeared in":["1991","1995","1983"]}
df = pd.DataFrame(d,columns = ["Programming Langauge","Designed by","Appeared in"])
print(df)

  Programming Langauge Designed by Appeared in
0               Python       Guido        1991
1                 Java       James        1995
2                  C++      Bjarne        1983


In [11]:
export_csv = df.to_csv(r'/home/AIML_Student/Documents/210962206/Week1/sheet4.csv',index = None,header = True)

In [15]:
import numpy as np
import pandas as pd
import sklearn
import scipy
import matplotlib 
import seaborn

In [73]:
#Convert a 1-D array into a 2-D array with 3 rows.
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [74]:
#Replace all odd numbers in the given array with -1
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a[a%2!=0] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [57]:
#Find the positions of:elements in x where its value is more than its corresponding element in y, and elements in x where its value is equals to its corresponding element in y.

x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

print(np.where(x > y))
print(np.where(x == y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [62]:
#Extract the first four columns of this 2-D array.
ar = np.arange(100).reshape(5,-1)
ar[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [70]:
#Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)

import random
np.random.randint(30,40,size = (10))

array([34, 32, 32, 31, 37, 31, 39, 36, 38, 39])

ADDITIONAL QUESTIONS

In [107]:
A = np.array([1, 2, 3,4, 5, 6,7, 8, 10])
A = A.reshape(3,-1)
B = np.array([7, 8, 10, 4, 5, 6, 1, 2, 3])
B = B.reshape(3,-1)
#Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract.
C = A+B
E = A-B
print(A)
print(B)
print(C)
print(E)

#Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C
print("A = ")
print(A.sum())
print(B.sum(axis=0))
print(C.sum(axis =1))

#Product of two matrices A and B, and print the resultant matrix D
D = np.cross(A,B)
print(D)

#Sort the elements of resultant matrix C and print the resultant Matrix E.      
E = np.sort(C)
print(E)

# Transpose the Matrix E and print the result
np.transpose(E)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[[ 7  8 10]
 [ 4  5  6]
 [ 1  2  3]]
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]
A = 
46
[12 15 19]
[31 30 31]
[[ -4  11  -6]
 [  0   0   0]
 [  4 -11   6]]
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]


array([[ 8,  8,  8],
       [10, 10, 10],
       [13, 12, 13]])